packages:
  - 'apps/*'
  - 'workers/*'

saveExact: true
allowBuilds:
  esbuild: true
  lefthook: true
  sharp: true
  workerd: true

catalogMode: strict

catalogs:
  astro:
    '@astrojs/check': 0.9.10
    '@astrojs/cloudflare': 14.2.3
    '@astrojs/mdx': 7.0.7
    '@astrojs/preact': 6.0.4
    '@astrojs/rss': 4.0.19
    '@astrojs/sitemap': 3.7.3
    '@astrojs/ts-plugin': 1.10.11
    astro: 7.0.5
  css:
    '@pandacss/dev': 1.12.0
    'kiso.css': 1.2.4
  format:
    '@prettier/plugin-oxc': 0.2.2
    prettier: 3.9.6
    prettier-plugin-astro: 0.14.1
  git:
    lefthook: 1.13.6
  preact:
    preact: 10.29.8
  runtime:
    '@types/node': 24.13.3
    typescript: 5.9.3
    '@typescript/native-preview': 7.0.0-dev.20260707.2
  cloudflare:
    wrangler: 4.125.0
    '@cloudflare/workers-types': 4.20260702.1
  storybook:
    '@storybook/addon-a11y': 10.5.10
    '@storybook/preact-vite': 10.5.10
    storybook: 10.5.10
  react:
    react: 19.2.8
  oxlint:
    oxlint: 1.79.0
  util:
    dayjs: 1.11.23
    sharp: 0.35.3
  pnpm:
    pnpm: 10.34.5
  hono:
    hono: 4.13.3

minimumReleaseAgeExclude:
  - '@astrojs/cloudflare@14.0.2'
  - '@astrojs/compiler-binding-darwin-arm64@0.3.0'
  - '@astrojs/compiler-binding-darwin-x64@0.3.0'
  - '@astrojs/compiler-binding-linux-arm64-gnu@0.3.0'
  - '@astrojs/compiler-binding-linux-arm64-musl@0.3.0'
  - '@astrojs/compiler-binding-linux-x64-gnu@0.3.0'
  - '@astrojs/compiler-binding-linux-x64-musl@0.3.0'
  - '@astrojs/compiler-binding-wasm32-wasi@0.3.0'
  - '@astrojs/compiler-binding-win32-arm64-msvc@0.3.0'
  - '@astrojs/compiler-binding-win32-x64-msvc@0.3.0'
  - '@astrojs/compiler-binding@0.3.0'
  - '@astrojs/compiler-rs@0.3.0'
  - '@astrojs/rss@4.0.19'
  - astro@7.0.4
  - '@cloudflare/workerd-darwin-64@1.20260630.1'
  - '@cloudflare/workerd-darwin-arm64@1.20260630.1'
  - '@cloudflare/workerd-linux-64@1.20260630.1'
  - '@cloudflare/workerd-linux-arm64@1.20260630.1'
  - '@cloudflare/workerd-windows-64@1.20260630.1'
  - miniflare@4.20260630.0
  - workerd@1.20260630.1
  - wrangler@4.106.0
