name: Cache and Install
description: Cache pnpm store and install dependencies

runs:
  using: composite

  steps:
    - name: Install Node.js
      uses: actions/setup-node@89d709d423dc495668cd762a18dd4a070611be3f

    - name: Install pnpm
      uses: pnpm/action-setup@f2b2b233b538f500472c7274c7012f57857d8ce0
      with:
        run_install: false

    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - name: Setup pnpm cache
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      shell: bash
      run: |
        pnpm install
