name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  typecheck:
    runs-on: ubuntu-24.04

    steps:
      - name: Setup
        uses: ./.github/composite-actions/cache-and-install

      - name: Typecheck
        shell: bash
        run: |
          pnpm run typecheck

  format:
    runs-on: ubuntu-24.04

    steps:
      - name: Setup
        uses: ./.github/composite-actions/cache-and-install

      - name: Format
        shell: bash
        run: |
          pnpm run format:check

  lint:
    runs-on: ubuntu-24.04

    steps:
      - name: Setup
        uses: ./.github/composite-actions/cache-and-install

      - name: Lint
        shell: bash
        run: |
          pnpm run lint:check
