name: CI (Web)

on:
  pull_request:
    branches:
      - main

jobs:
  typecheck:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493

      - name: Setup
        uses: ./.github/composite-actions/cache-and-install

      - name: Typegen
        working-directory: apps/web
        run: |
          pnpm run cf-typegen

      - name: Sync
        working-directory: apps/web
        run: |
          pnpm astro sync

      - name: Typecheck
        working-directory: apps/web
        shell: bash
        run: |
          pnpm run typecheck

  format:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493

      - name: Setup
        uses: ./.github/composite-actions/cache-and-install

      - name: Format
        working-directory: apps/web
        shell: bash
        run: |
          pnpm run format:check

  lint:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493

      - name: Setup
        uses: ./.github/composite-actions/cache-and-install

      - name: Typegen
        working-directory: apps/web
        run: |
          pnpm run cf-typegen

      - name: Sync
        working-directory: apps/web
        run: |
          pnpm astro sync

      - name: Lint
        shell: bash
        working-directory: apps/web
        run: |
          pnpm run lint:check
