name: Deploy to Cloudflare Workers (Web)

on:
  pull_request:
    branches:
      - "main"
    types: [closed]

jobs:
  deploy-to-cloudflare-workers:
    runs-on: ubuntu-latest
    outputs:
      should_deploy: ${{ steps.check.outputs.should_run }}
    steps:
      - name: Checkout
        uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493

      - name: Setup
        uses: ./.github/composite-actions/cache-and-install

      - name: Deploy to Cloudflare Workers
        if: ${{ github.event.pull_request.merged == true && github.base_ref == 'main' }}
        working-directory: apps/web
        run: pnpm run deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
